[package]
name = "drops_moves_copies"
version = "0.1.0"
authors = ["Orhan Aygün <orh.aygun@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
